/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StartupFunding } from './StartupFunding.js';
export * as factories from './factories/index.js';
export { StartupFunding__factory } from './factories/StartupFunding__factory.js';