/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StartupFundingInterface extends Interface {
    getFunction(nameOrSignature: "createStartup" | "getInvestment" | "getInvestmentCount" | "getStartup" | "invest" | "startupCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InvestmentMade" | "StartupCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createStartup', values: [string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInvestment', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInvestmentCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getStartup', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startupCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createStartup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestmentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getStartup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startupCount', data: BytesLike): Result;
  }

  
    export namespace InvestmentMadeEvent {
      export type InputTuple = [startupId: BigNumberish, investor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [startupId: bigint, investor: string, amount: bigint];
      export interface OutputObject {startupId: bigint, investor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StartupCreatedEvent {
      export type InputTuple = [startupId: BigNumberish, founder: AddressLike, name: string, fundingGoal: BigNumberish];
      export type OutputTuple = [startupId: bigint, founder: string, name: string, fundingGoal: bigint];
      export interface OutputObject {startupId: bigint, founder: string, name: string, fundingGoal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StartupFunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): StartupFunding;
    waitForDeployment(): Promise<this>;

    interface: StartupFundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createStartup: TypedContractMethod<
      [_name: string, _description: string, _fundingGoal: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getInvestment: TypedContractMethod<
      [_startupId: BigNumberish, _investmentIndex: BigNumberish, ],
      [[string, bigint] & {investor: string, amount: bigint }],
      'view'
    >
    

    
    getInvestmentCount: TypedContractMethod<
      [_startupId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getStartup: TypedContractMethod<
      [_startupId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, founder: string, name: string, description: string, fundingGoal: bigint, totalRaised: bigint, active: boolean }],
      'view'
    >
    

    
    invest: TypedContractMethod<
      [_startupId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    startupCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createStartup'): TypedContractMethod<
      [_name: string, _description: string, _fundingGoal: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getInvestment'): TypedContractMethod<
      [_startupId: BigNumberish, _investmentIndex: BigNumberish, ],
      [[string, bigint] & {investor: string, amount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestmentCount'): TypedContractMethod<
      [_startupId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getStartup'): TypedContractMethod<
      [_startupId: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, boolean] & {id: bigint, founder: string, name: string, description: string, fundingGoal: bigint, totalRaised: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'invest'): TypedContractMethod<
      [_startupId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'startupCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'InvestmentMade'): TypedContractEvent<InvestmentMadeEvent.InputTuple, InvestmentMadeEvent.OutputTuple, InvestmentMadeEvent.OutputObject>;
getEvent(key: 'StartupCreated'): TypedContractEvent<StartupCreatedEvent.InputTuple, StartupCreatedEvent.OutputTuple, StartupCreatedEvent.OutputObject>;

    filters: {
      
      'InvestmentMade(uint256,address,uint256)': TypedContractEvent<InvestmentMadeEvent.InputTuple, InvestmentMadeEvent.OutputTuple, InvestmentMadeEvent.OutputObject>;
      InvestmentMade: TypedContractEvent<InvestmentMadeEvent.InputTuple, InvestmentMadeEvent.OutputTuple, InvestmentMadeEvent.OutputObject>;
    

      'StartupCreated(uint256,address,string,uint256)': TypedContractEvent<StartupCreatedEvent.InputTuple, StartupCreatedEvent.OutputTuple, StartupCreatedEvent.OutputObject>;
      StartupCreated: TypedContractEvent<StartupCreatedEvent.InputTuple, StartupCreatedEvent.OutputTuple, StartupCreatedEvent.OutputObject>;
    
    };
  }